apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-10-10T23:01:00Z"
  generation: 1
  labels:
    app: hashgenerator-dep
  name: hashgenerator-dep
  namespace: mooc
  resourceVersion: "35844597"
  uid: 19390b77-06a3-4b82-aa61-c4028a2b2b32
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hashgenerator-dep
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hashgenerator-dep
    spec:
      containers:
      - image: jakousa/dwk-app1
        imagePullPolicy: Always
        name: dwk-app1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-10-10T23:01:10Z"
    lastUpdateTime: "2025-10-10T23:01:10Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-10-10T23:01:00Z"
    lastUpdateTime: "2025-10-10T23:01:10Z"
    message: ReplicaSet "hashgenerator-dep-85898f9997" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

